spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  cache:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=60s

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

## ???? ??? ???
jwt:
  secret:
    key: ZnNhZGZzYWRmbHNhZGpmbDEyMzEyMzEyMzEyM2wya2ozbDEzajJsMzEzbDIxajNsMTJqc2Q=


logging:
  level:
    root: info                       # ✅ 전체 로그 기본 레벨 유지 (error, warn 포함)
    org.hibernate.SQL: debug         # SQL 로그
    org.hibernate.orm.jdbc.bind: trace  # 바인딩된 파라미터 출력